###

The meta.toc object is an MDAST generated by tools/build-routes.imba even though
it is an HTML page. https://github.com/syntax-tree/mdast

###

import { MarkdownToc } from "./MarkdownPage"

export default tag HtmlPage
	prop meta
	prop table
	prop html
	get tocSide
		isString(meta.toc) ? toc : "left"
	<self.front-matter-page>
		if meta.showToc and tocSide is "left"
			<div.fmp-toc>
				<MarkdownToc table=table>
		<.fmp-content .fmp-content-with-toc=showToc .fmp-content-full=(not showToc)>
			<div innerHTML=html>
		if meta.showToc and tocSide is "right"
			<div.fmp-toc>
				<MarkdownToc table=table>
